### PR TITLE
Fix crash in Linux Joystick Implementation

### PR DESCRIPTION
**Pull request by a1rwulf**
This fixes a crash on linux.
First commit temporarily fixes the crash when axis/buttons are empty.
Second one adds proper initialize for the JoystickLinux class.

### CODE REVIEW

**Comment by garbear** [comment]
oops, didn't get notified of the updated commits

is there a reason you included `CJoystickSDL::Deinitialize()`? `CJoystick::Deinitialize()` will still be called if it's omitted... and besides neither Deinitialize() actually does anything

everything else looks good

**Comment by a1rwulf** [comment]
sorry, did not add any comment, my fail.
the only reason that I included ```CJoystickSDL::Deinitialize``` was for clarity, so one without deeper knowledge of the codebase and inheritance hierarchy could add deinitialize code for SDL easily.
As this should not get called frequently I think there's no performance degrade and it may even get optimized out by the compiler.
Of course now after digging into the code a bit, it is quite clear how it works so if you prefer I'll just remove it.
Let me know your thoughts.

**Comment by garbear** [comment]
i prefer removed, if we ever need deinitialization code for sdl we can add it back

**Comment by a1rwulf** [comment]
here we go :)

**Comment by garbear** [comment]
merged. thanks

**Pull request merged**
